---
title: "`RAPToR` - Showcase"
output: 
  BiocStyle::html_document:
    toc: true
    toc_depth: 3
    code_folding: hide
  rmarkdown::pdf_document:
    toc: true
    toc_depth: 3
    number_sections: yes
    includes:
      in_header: "../inst/tex/preamble.tex"
subtitle: "`r BiocStyle::pkg_ver('RAPToR')`"
vignette: >
  %\VignetteIndexEntry{RAPToR-showcase}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: ../inst/REFERENCES.bib
author: Romain Bulteau
date: "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.Date(), '%B %Y')`"
---

<br>

This vignette showcases different uses for `RAPToR`.

<br>

# Improving Differential Expression analysis with age estimates

```{r sc_1, child = "sc_1.Rmd"}

```

<br>
<br>

# Staging samples cross-species 
```{r sc_2, child = "sc_2.Rmd"}

```

<br>
<br>

# Capturing tissue-specific development

```{r sc_3, child = "sc_3.Rmd"}

```

<br>
<br>
[Back to top](#top)

<hr>

# References {.unnumbered}
<div id="refs"></div>

<hr>
# SessionInfo {.unnumbered}
```{r sc_restrictwidth, include=FALSE}
options(width = 80)
```

```{r sc_sessInfo, collapse=FALSE, class.source = 'fold-show'}
sessionInfo()
```
